In [4]:
import xgboost

import shap

# train XGBoost model
X, y = shap.datasets.adult(n_points=2000)
model = xgboost.XGBClassifier().fit(X, y)

# compute SHAP values
explainer = shap.Explainer(model, X)
shap_values = explainer(X)

shap_values.values[:, 1], shap_values.values.shape, set(y), X.shape

(array([ 0.32043266,  0.09502171,  0.22713668, ..., -1.2461332 ,
         0.20193397,  0.11154147]),
 (2000, 12),
 {np.False_, np.True_},
 (2000, 12))

In [ ]:
# train XGBoost model
X, y = shap.datasets.california(n_points=2000)
model = xgboost.XGBRegressor().fit(X, y)

# compute SHAP values
explainer = shap.Explainer(model, X)
shap_values = explainer(X)

shap_values.values[:, 1], shap_values.values.shape, X.shape

(array([-0.01722049,  0.04664123,  0.09204117, ...,  0.03051694,
        -0.01808641,  0.10571885]),
 (2000, 8),
 (2000, 8))

In [6]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

X, y = load_iris(return_X_y=True)
model = LogisticRegression(random_state=0).fit(X, y)

# compute SHAP values
explainer = shap.Explainer(model, X)
shap_values = explainer(X)

shap_values.values[:, 1], shap_values.values.shape, set(y), X.shape

/Users/rwkoops/anaconda3/envs/probatus/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


(array([[ 0.44839605, -0.14589609, -0.30249996],
        [-0.03478935,  0.01131952,  0.02346982],
        [ 0.15848481, -0.05156672, -0.10691809],
        [ 0.06184773, -0.0201236 , -0.04172413],
        [ 0.54503313, -0.17733921, -0.36769392],
        [ 0.83494436, -0.27166858, -0.56327579],
        [ 0.35175897, -0.11445297, -0.237306  ],
        [ 0.35175897, -0.11445297, -0.237306  ],
        [-0.13142643,  0.04276265,  0.08866378],
        [ 0.06184773, -0.0201236 , -0.04172413],
        [ 0.64167021, -0.20878233, -0.43288787],
        [ 0.35175897, -0.11445297, -0.237306  ],
        [-0.03478935,  0.01131952,  0.02346982],
        [-0.03478935,  0.01131952,  0.02346982],
        [ 0.93158144, -0.3031117 , -0.62846974],
        [ 1.31812976, -0.42888419, -0.88924557],
        [ 0.83494436, -0.27166858, -0.56327579],
        [ 0.44839605, -0.14589609, -0.30249996],
        [ 0.73830729, -0.24022546, -0.49808183],
        [ 0.73830729, -0.24022546, -0.49808183],
        [ 0.35175897